spring.application.name=dabble
server.port=3366
#URL
app.upload.dir=file:uploads/
base_url=http://localhost:3366/
client_url=http://localhost:3000/
admin_url=http://localhost:8668/
check-payment_url=http://localhost:3000/check-payment
avatar-url=https://ui-avatars.com/api/?name=
#Image
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB
#Static files
spring.web.resources.static-locations=classpath:/static/,file:/app/uploads/
#Swagger
springdoc.swagger-ui.path=/
#Cassandra
spring.cassandra.keyspace-name=dabble_messenger
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=
spring.cassandra.username=
spring.cassandra.password=
spring.cassandra.local-datacenter=datacenter1
#SQL
spring.datasource.url=jdbc:mysql://127.0.0.1:9307/yourdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
#JWT
JWT_SecretKey=
JWT_Expiration_Time=10
#Turnstile
Turnstile_SecretKey=
Turnstile_ApiUrl=https://challenges.cloudflare.com/turnstile/v0/siteverify
#Redis
spring.data.redis.host=127.0.0.1
spring.data.redis.port=9379
token.expiration-minutes=5
#google
google.client-id=
# PayPal
paypal.client.id=
paypal.client.secret=
paypal.mode=sandbox
spring.jackson.time-zone=UTC

